language: java
sudo: false
jdk: oraclejdk8
addons:
  apt:
    packages: oracle-java8-installer
script: mvn clean verify
after_success:
- mvn clean test jacoco:report coveralls:report
before_deploy:
- mvn clean package -DskipTests=true -Dproject.finalName=DroneSimulator$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Y6FpU4ptKfr/NglV2Kw4ATaXnNdytHf8KhDtDQcihg9bUO9bRE5oV83kxt7emTB6LmwIxqjlFJBkHrF/SzexM3igFkv/pXqBuqBgRQ1mvon1J6eFRvtgcOt9VdsVe2FtjV/0UfflSSt1rcujAR1ee4wN1/WX+yLACv8A1N37TYZ51tLAvSRbnJ381yLKCI4ulpkVa7zxjUFPr2QJOUP2xQLp1soXhh6eXsnikqNoqStMuWOw0P1tRBoonroErQft2TIMaeNhCaZIYg9D85SEhCmYS3bOM+Ku+eBk1De2zETic7Vl/1ioJuhkDa5VZr8mS2gGAX4PwVPh2uLjeQh5u0sByQVQK+Vd9vleHsNhpQulaPGRgbeGxLNVNe5L9Agzpp0p+sFhChURwklszh0ISshSf0pBg+GnyF7kAbGaGK6MkPi7cfAxd0vYOAvB4D6IM190SGHBucmecQoS3p6SuvnOsRBFg4U1asNPu5E/vGAP1eFYv3OI94XqC9nq+FXbDSBFj5RNudfMHOoWPtksqQNMNLA9u//u0lKBdOmjUT/a4lEI2RJe2vvp39ZJrWe+JUY+czE7Aq4+fnBJay8x8pryNhlZtBfDNIB5fkBdCA9WNQxwQ/MJaN47RloMHMys+kY3Nstg8Ll8x8Vy2IRuEv3QmKQa42ciog/vqixWJUQ=
  file: target/DroneSimulator$TRAVIS_TAG
