language: java
sudo: false
jdk:
  oraclejdk8
addons:
  apt:
    packages:
      oracle-java8-installer
script: mvn clean verify
after_success:
- mvn clean test jacoco:report coveralls:report
before_deploy:
- mvn clean package -DskipTests=true -Dproject.finalName=DroneSimulator$TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: Ucm9JvReChdS2uH6DnfdMbaeJmBN4ldFFThuqG3RJ5UUCbmFLODxPIDYucktWff2qN5e6rHv4bV/L+s5WCRhm3QDyonId9fttARRFlsP0ZFfDrAYwOmUiZYCjKGqrmAi06pCRFNCE8gpej6yhzsklhznTYk36CxRXsaQcE7j4D44b3ljulrbr+RNv79ZQl5OO/VFauraqmlqNntroxrL9szSRHSpM8slIsGXCWloF7LqwpCjVT49kml/l7pAR9wyHa0fr+bgLnqnLh8TfFPxq5lueao2oRv6Njib3vuZDWn7FUNdCYV7InvUwwwsH/GtsSdXvA5FdIIANI5i7dyOuWyyfSuf3GEPF3pMWqfVnWzoiIF0hc8supE2RhoIAV40snrTqGeiNRgdnLUe2Ejo5+2QQ4MVuORg4I8foI1ZNtsLEw61In3zzeVi3yZ27uGkdfObyMDoVfvyDMbMWCNoCbNtNSWaxJTe9ysKstHUG2lRDAfcl+rWDJPhScDiDWShSCJaaFS5ZXoTcqWHZrkbm0yUt3hTE61Of/9kXjEmwhP13jNL7dmwns+qT6Q3d4iy131edu5MXfa4DeyPCr6fLQjp56I6BY5w2p4qifqA66psIE58YfI1322FNxiFaKUDZQY/AiVgBmpVmqAUYqY5dKn9Vki+oxIs/LF/+nEl+Lk=
  file: target/DroneSimulator$TRAVIS_TAG.jar
  on:
    repo: dsajgiouawj/DroneSimulator
    all_branches: true
    tags: true
